// src/dom.js

export const elements = {
    dropZone: document.getElementById('dropZone'),
    settingsFile: document.getElementById('settingsFile'),
    fileInfo: document.getElementById('fileInfo'),
    promptsSection: document.getElementById('promptsSection'),
    commonSettingsSection: document.getElementById('commonSettings'),
    selectParamsSection: document.getElementById('selectParamsSection'),
    defineValuesSection: document.getElementById('defineValuesSection'),
    generateSection: document.getElementById('generateSection'),
    batchNameTemplate: document.getElementById('batchNameTemplate'),
    batchNamePreview: document.getElementById('batchNamePreview'),
    variableButtons: document.querySelector('.variable-buttons'),
    xParam: document.getElementById('xParam'),
    yParam: document.getElementById('yParam'),
    zParam: document.getElementById('zParam'),
    xParamInfo: document.getElementById('xParamInfo'),
    yParamInfo: document.getElementById('yParamInfo'),
    zParamInfo: document.getElementById('zParamInfo'),
    enableZ: document.getElementById('enableZ'),
    zParamGroup: document.getElementById('zParamGroup'),
    valueContainers: document.getElementById('value-containers'),
    xValues: document.getElementById('xValues'),
    yValues: document.getElementById('yValues'),
    zValues: document.getElementById('zValues'),
    addXValueBtn: document.getElementById('addXValueBtn'),
    addYValueBtn: document.getElementById('addYValueBtn'),
    addZValueBtn: document.getElementById('addZValueBtn'),
    generateBtn: document.getElementById('generateBtn'),
    loadingSpinner: document.getElementById('loadingSpinner'),
    results: document.getElementById('results'),
    fileCount: document.getElementById('fileCount'),
    downloadBtn: document.getElementById('downloadBtn'),
    fileList: document.getElementById('fileList'),
};

export const promptsElements = {
    animatePrompts: document.getElementById('animatePrompts'),
    fixedPromptsContainer: document.getElementById('fixedPromptsContainer'),
    animatedPromptsContainer: document.getElementById('animatedPromptsContainer'),
    positivePrompt: document.getElementById('positivePrompt'),
    negativePrompt: document.getElementById('negativePrompt'),
    animatedPromptsFields: document.getElementById('animatedPromptsFields'),
    addKeyframeBtn: document.getElementById('addKeyframeBtn'),
};

export const commonSettingsElements = {
    max_frames: document.getElementById('max_frames'),
    fps: document.getElementById('fps'),
    durationDisplay: document.getElementById('durationDisplay'),
    sampler: document.getElementById('sampler'),
    seed: document.getElementById('seed'),
    seed_behavior: document.getElementById('seed_behavior'),
    steps: document.getElementById('steps'),
    noise_type: document.getElementById('noise_type'),
    border_mode: document.getElementById('border_mode'),
    strength_schedule: document.getElementById('strength_schedule'),
    cfg_scale_schedule: document.getElementById('cfg_scale_schedule'),
    noise_schedule: document.getElementById('noise_schedule'),
    diffusion_cadence: document.getElementById('diffusion_cadence'),
    color_coherence: document.getElementById('color_coherence'),
};

export const animationElements = {
    modeRadios: document.querySelectorAll('input[name="animation_mode"]'),
    container2D: document.getElementById('animationMode2DContainer'),
    container3D: document.getElementById('animationMode3DContainer'),
    zoom_2d: document.getElementById('zoom_2d'),
    translation_x_2d: document.getElementById('translation_x_2d'),
    translation_y_2d: document.getElementById('translation_y_2d'),
    rotation_2d: document.getElementById('rotation_2d'),
    translation_x_3d: document.getElementById('translation_x_3d'),
    translation_y_3d: document.getElementById('translation_y_3d'),
    translation_z_3d: document.getElementById('translation_z_3d'),
    rotation_3d_x: document.getElementById('rotation_3d_x'),
    rotation_3d_y: document.getElementById('rotation_3d_y'),
    rotation_3d_z: document.getElementById('rotation_3d_z'),
};
